### ISSUE TITLE
Apple/Google privacy preserving COVID-19 contact tracing.

### ISSUE THREAD

**Issue by ghost** [AU-COVIDSafe/mobile-ios#10]
Good morning. Can you please add support for the Apple/Google privacy preserving COVID-19 contact tracing. Thanks

https://www.apple.com/covid19/contacttracing

**Comment by covidsafe-support** [comment]
Hi @benos5000, thanks for raising this. We are working with Apple and Google as they develop contact tracing technology that could enhance the COVIDSafe application and, when appropriate, we will communicate how the COVIDSafe application can leverage the technology.

**Comment by balupton** [comment]
From the wikipedia page:

> Transitioning from BlueTrace to ENF presented several issues, most notably that, as the app cannot run both protocols simultaneously,[107] any protocol change would be a hard cut between versions. This would result in the app no longer functioning for any users who had not yet updated to the ENF version of the app. Additionally, the two protocols are almost completely incompatible,[81][80] meaning the vast majority - all but the UI - of the COVIDSafe app would have to be redeveloped. Similarly, because of the change from a centralised reporting mechanism to a decentralised one, very little of the existing server software would be usable.[108] The role of state and territory health authorities in the process would also change significantly, as they would no longer be responsible for determining and contacting encounters.[108] This change would involve retraining health officials and penning new agreements with states and territories.
> 
> Up until at least 18 June 2020, the DTA was experimenting with ENF,[109] however in an interview with The Project held on 28 June 2020, Deputy Chief Medical Officer Dr Nick Coatsworth stated COVIDSafe would "absolutely not" transition to ENF.[110] He reasoned the government would never transition to any contact tracing solution without human-in-the-loop reporting,[111][112] something that no decentralised protocol can support.
> 
> https://en.wikipedia.org/wiki/COVIDSafe

Sounds like it will never happen as the government is arguing sunken costs and necessity for government interception.

How likely is it that we will see this issue resolved? As it seems it is closer to never than probably.

**Comment by HendX** [comment]
From iOS 13.7 (released today in beta), and iOS 14 (coming very soon), the Exposure Notifications framework will be enabled without requiring installation of an app.

This means exposures will be detected even if they don't have an app installed. This functionality will **NOT** be enabled in Australia though, since COVIDSafe doesn't use Exposure Notifications.

_Note: Anybody running an iPhone 6s or newer (released 2015) has a device capable of running EN_

**Comment by HendX** [comment]
@covidsafe-support Any chance of an updated statement justifying why the app is not using Exposure Notifications?

Considering the current app detects about "25-50% between two locked iPhones", whereas Exposure Notifications detects 99+%.

**Comment by HendX** [comment]
Note that as of today, iOS 13.7 has been released.

This allows exposure notifications to be enabled without installing an app.

If Australia supported this system the uptake would be much higher.

**Comment by calrt** [comment]
What will be interesting is if an inquiry is conducted into the failings of this app and it's revealed that changing to the exposure notifications API could have reduced the health and economic impact of the virus.

Was there a publicly available definition for success of the COVIDSafe app? If not, it was set up for failure based on at least some part a lack of clear objectives and accountability.

I was an advocate for this app when it was released initially but like others, trust was pretty quickly lost when it was shown to be ineffective and it was depleted even further when more money was spent on advertising something that wasn't working.

I understand that decisions have to be made on the science and knowledge that are available at the time, and the science community is continuing to develop its awareness of the virus and how to tackle it. Given that, i'm definitely not envious of the people having to make these decisions and understand there are endless difficulties on a project like this.

However I think there is an obligation for an explanation on why the current system is better than the notifications API.

Is anyone aware of data on the effectiveness of the notifications api in countries that have used it? Would be interesting to see whether it would actually be more successful.

**Comment by HendX** [comment]
Note that as of today, New Zealand is now also using Exposure Notifications in their app.

This means if Australia adopt it, COVIDSafe would be compatible with the New Zealand app. This means if a travel bubble were opened then exposures could easily be traced across the Tasman.

**Comment by balupton** [comment]
UK just added support for the Exposure Notifications API too via their app.

I've added Australia to the non-adopters section of the Exposure Notifications API page:
https://en.wikipedia.org/wiki/Exposure_Notification#Non-adopters

**Comment by rekkisomo** [comment]
Why was this closed w/o reason? It seems the commit history and the newest version doesn’t implement this yet.

**Comment by jamver** [comment]
> Hi @benos5000, thanks for raising this. We are working with Apple and Google as they develop contact tracing technology that could enhance the COVIDSafe application and, when appropriate, we will communicate how the COVIDSafe application can leverage the technology.

@covidsafe-support, is this a "Closed, won't fix", or is there another reason this has been closed?

**Comment by chendo** [comment]
What is the point of asking for feedback if you're just going to close the issue with no comment?

https://twitter.com/DTA/status/1333216553140011009

**Comment by balupton** [comment]
If they implemented Exposure Notifications API then how would such a simple UI wrapper around an API justify the millions they receive.

The biggest failure of the Exposure Notifications API is the only allowing the government to make the wrapper app. As government worker interests hardly align with the interests of the people.

We are probably better off spending our time not campaigning the government but campaigning Apple and Google to lift the government app restriction.

**Comment by HendX** [comment]
> If they implemented Exposure Notifications API then how would such a simple UI wrapper around an API justify the millions they receive.
> 

@balupton this forum is one of the few ways it is possible to engage with DTA over the app. Please don't ruin it with snark or comments that may result in moderation or closure.

Yes there is extreme frustration by tech experts in Australia at the dogmatic rejection of the Exposure Notifications framework, but this discourse on here isn't helpful.

As the above comment states, for it to work effectively it should complement existing efforts and integrate directly with the contact tracing efforts of the state governments.

It is a heavily-guarded framework by Apple because it is very powerful, and is also specifically built for governments to use in their efforts in fighting COVID-19.
