### ISSUE TITLE
MTU issue with long payloads prevents iOS to iOS exchanges

### ISSUE THREAD

**Issue by jimmo** [AU-COVIDSafe/mobile-ios#11]
This relates to an issue was first reported privately on 12th June 2020. The background is that the V2 encryption scheme resulted in payloads that are longer than the iPhone's MTU, so a GATT "long read" must be used to fetch the payload in MTU-sized chunks.

The initial issue was that the long read wasn't handled correctly in PeripheralController.swift `didReceiveRead`, as it ignored the `offset` parameter.

A fix for this was attempted in v1.6 (see https://github.com/AU-COVIDSafe/mobile-ios/commit/2063cea613a15f2f1abef6b3f3d735ae5ce398c4) which now uses the offset parameter. However, each chunked read will get the offset data from accessing `EncounterMessageManager.getAdvertisementPayload`, which uses the `advertisementPayload` property, which will use the cached TempID, but encrypt every time with a unique nonce, generating a unique payload each time.

The result is that the re-assembled payload will be made up of chunks that were each encrypted with a different nonce. The payload will still be very likely to be valid JSON (unlike before the fix), and therefore logged to the encounter database, however the server will be unable to decrypt it.

It may in fact be possible to "rescue" any previously recorded payloads if you assume that the nonces used are sequential from the nonce included in the first fragment (although it will still only be a partial recovery due to the alignment of the MTU and the AES block size, but this might still be enough to recover enough of a TempID for contact tracing purposes)

**Comment by covidsafe-support** [comment]
Hi @jimmo - thanks for the issue report. This is actually an issue that we picked up in internal testing not long before you posted this, and we are currently working on a fix. We'll keep this issue open to track progress and let you know when we believe we have released a fix.

**Comment by covidsafe-support** [comment]
Hi @jimmo - just letting you know we have released v1.8 of COVIDSafe for iOS which should have addressed this MTU issue, please let us know if you believe otherwise. Thank you again for reporting this issue.
