### ISSUE TITLE
Register without phone number

### ISSUE THREAD

**Issue by ghost** [AU-COVIDSafe/mobile-ios#13]
Please add the ability to register without a phone number as I do not want my phone number stored in an online database.

**Comment by covidsafe-team** [comment]
Hi Ghost,
Thanks for your comment. Phone number will remain a registration requirement for the foreseeable future as it provides a method for contact tracing staff to contact you if needed.

**Comment by jamver** [comment]
I don't believe providing a phone number is a legal requirement, only a convenience.

This aspect of privacy could easily be solved by providing allowing registration with an email address, or requesting and allowing push notification back to the app.

Refusing to add this feature or de-prioritising its development must certainly have an impact on the overall number of registered users, and therefore efficacy of the this aspect of the pandemic response programme.
