### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by stragu** [AU-COVIDSafe/mobile-ios#16]
It is difficult to read a diff in this repository, as new versions are released as one single commit.

It would be very helpful for independent reviewers to be provided with a changelog of what has been changed / added / fixed between versions.

(By the way, thank you for opening the Issues feature on this repository.)

**Comment by covidsafe-support** [comment]
Hi @stragu - thanks for the suggestion. We've added this to our backlog to look in to further.
