### ISSUE TITLE
v1.9 - cleanupScannedPeripherals doesn't appear to be thread-safe

### ISSUE THREAD

**Issue by yaakov-h** [AU-COVIDSafe/mobile-ios#19]
The new method `cleanupScannedPeripherals` is called from three locations:

- [`CentralController.peripheral(_:didUpdateValueFor:error:)`](https://github.com/AU-COVIDSafe/mobile-ios/blob/5455912f0af7dfe01931b3c3227477553d9a5467/CovidSafe/CentralController.swift#L450)
- [`CentralController.centralManager(_:didDiscover:advertisementData:rssi:)`](https://github.com/AU-COVIDSafe/mobile-ios/blob/5455912f0af7dfe01931b3c3227477553d9a5467/CovidSafe/CentralController.swift#L271)
- [A NotificationCenter observer](https://github.com/AU-COVIDSafe/mobile-ios/blob/5455912f0af7dfe01931b3c3227477553d9a5467/CovidSafe/CentralController.swift#L52)

The first two are all called from the CentralController's private Dispatch Queue, which is where all of the `CBCentralManagerDelegate` methods are invoked, as well as I believe the `CBPeripheralDelegate` methods.

However, the notification is dispatched to the main queue, which means that it may attempt to access or modify local state at the same time as the Core Bluetooth delegate methods, which could lead to corruption, inconsistent state, leaks, crashes, etc.

Unless there's something I'm missing, it would be better for the notification observer's work to be dispatched to the private queue, so that all Bluetooth-related work is serialized on the same queue.

**Comment by covidsafe-support** [comment]
Hi @yaakov-h - thank you for bringing this to our attention. A backlog task has been created to look into this, and we will update this Github issue if we have progress to report or need any clarification.

**Comment by yaakov-h** [comment]
This was fixed in v1.10, code dumped 18th August.
