### ISSUE TITLE
Latest updates on BlueTrace code...

### ISSUE THREAD

**Issue by GQAdonis** [AU-COVIDSafe/mobile-ios#23]
I have been looking for updates to the BlueTrace protocol that addresses battery life issues and background operations that was supposed to appear in a 2.1 version.  I have asked on the OpenTrace project about these updates and gotten no answers.

Can anyone here tell me how to keep the BlueTrace mobile code updated and where to get the latest version?  Is that version being used here?

**Comment by covidsafe-team** [comment]
Hi GQAdonis,
Sorry for the delay in responding to you. I will see if we have any info we can share on this.

**Comment by covidsafe-team** [comment]
Hi @GQAdonis - Sorry but we aren't able to help you with any info on BlueTrace.
