### ISSUE TITLE
No updates for 1.12 or 1.13

### ISSUE THREAD

**Issue by SirLionfire** [AU-COVIDSafe/mobile-ios#24]
Where are the updates for 1.12 (2020-09-25) and 1.13 (2020-10-13)?  Changes for the android version also seem to be missing.

**Comment by covidsafe-team** [comment]
Hi SirLionfire,
Thanks for your comment. We added 1.14 on November 10. We expect to get back to releasing the code closer to each release from here on.

**Comment by balupton** [comment]
v1.12 and v1.13 must have been the mass surveillance ones
