### ISSUE TITLE
QR code check-in integration

### ISSUE THREAD

**Issue by chrisleekr** [AU-COVIDSafe/mobile-ios#26]
In order to encourage people to use COVID Safe app, why don't we integrate contactless QR check-in system nationally (or each state)?

I understand many people are using COVID Safe app; however unless more people are using this app, it won't be useful. 

QR check-in service will be easy to integrate with this app and just simply need to build up the database which discards the recorded data after 14 days. We already write the name and phone number or email to pen/paper when we enter any hospitality premises. So it won't be an issue to save the basic info into the app and do QR check-in as long as the information will be destroyed after a certain time.

The QR check-in integration will make people using/downloading this app more. And contact tracing will be much faster and easier than just pen/paper in the shop. 

Any thought?

**Comment by codyhamilton** [comment]
The app could be used already to provide a service similar to this. If a small cafe for example just installed it on their point of sale tablet, it would register contacts automatically.

If any of those contacts tested positive, the cafe would be contacted and the registered contacts could be uploaded. 

The obvious caveats are range (may need multiple devices), accuracy and the fact you’re depending on everyone having the app installed. You’d have to consider whether an honour system (only sign in if you don’t have the app) would be respected enough to make it work. Plus there are ethical concerns - we are not mandating the app, but it could be abused to coerce adoption

**Comment by GZidar** [comment]
I do not understand why this functionality is not being included in the app. As a result of this oversite each state and territory is coming up with it's own solution that may or may not be functional across borders so having a national system in place to deliver this feature seems to make sense.

I have read that "the app does not track the user's location" as a reason preventing using this tool to provide QR code check in but that also makes no sense. Terms and conditions can be changed and even beyond that it would be trivially easy to do the QR code check-in feature without the need to link that data to the contact tracing data or to store location along side any contact tracing data.

I would have thought that adding this feature would drive app usage which is kind of the point. The app is useless if only a small number of people are using it - and if the app were also being used to provide the QR code check-in feature then more people would use it.

Sadly I think that ship has sailed as the states and territories are either already using some other solution or well down the track of implementing their own. This seems like a major missed opportunity for this solution.

**Comment by covidsafe-team** [comment]
Thanks @chrisleekr  for your considered feedback. As [noted here](https://github.com/AU-COVIDSafe/mobile-android/issues/30#issuecomment-739706281 ) COVIDSafe will continue to focus on Bluetooth tracing. QR Code integration is not currently within the scope of COVIDSafe.
