### ISSUE TITLE
Still doesn't use Exposure Notifications framework

### ISSUE THREAD

**Issue by jarrodrobins** [AU-COVIDSafe/mobile-ios#28]
Why does the government continue to refuse to use the Apple/Google Exposure Notifications framework?

Why won't CovidSafe use the correct solution that allows Bluetooth use in the background - which might actually save lives?

Simply patching a fundamentally flawed app with "Herald" will not solve the problem.

Instead of spending millions on flawed technology, I, as well as countless other iOS developers in Australia would be more than happy to develop a working version of the app with the Exposure Notifications framework pro bono. 

Australia deserves a CovidSafe app that actually works.

**Comment by covidsafe-team** [comment]
Thanks @jarrodrobins -  but we are seeking feedback on the new code using the Herald protocol. More info on how Herald works can be found here https://www.dta.gov.au/news/covidsafe-captures-close-contacts-new-herald-protocol

You can download a demo of Herald from here https://github.com/vmware/herald-for-ios

**Comment by jarrodrobins** [comment]
Thanks @covidsafe-team, but I'm telling you (as I'm sure you're well and truly aware) that Herald will not solve the fundamental problem. Just use Exposure Notifications. Apple and Google built it for the purpose of using Bluetooth in the background. Herald is unnecessary and won't work anyway.

**Comment by bencmorrison** [comment]
It seems unwise to not use the Exposure Notifications that Apple and Google have put forward. What is the reason it is believed the application should not use them but instead the flawed Herald protocol?

**Comment by n0rt0nthec4t** [comment]
Not to mention, the Herald protocol was used in the UKs contact tracing app, which now they have ditch and are using the Apple and Google exposure frameworks. Stop wasting tax payer money developing this flawed application, admit it was a failure and move on.

**Comment by n0rt0nthec4t** [comment]
> Instead of spending millions on flawed technology, I, as well as countless other iOS developers in Australia would be more than happy to develop a working version of the app with the Exposure Notifications framework pro bono.

Or just implement Express notifications for the Apple framework, no app required at all.. But, that would be just too simple ;-)

**Comment by covidsafe-team** [comment]
Hi @n0rt0nthec4t that is incorrect - see our tweet earlier today https://twitter.com/DTA/status/1333216550350770177

**Comment by jarrodrobins** [comment]
@covidsafe-team Lipstick on a pig. You still won’t answer why you refuse to use the Apple/Google solution that have developed for the specific purpose of using Bluetooth in the background.

**Comment by n0rt0nthec4t** [comment]
> Hi @n0rt0nthec4t that is incorrect - see our tweet earlier today https://twitter.com/DTA/status/1333216550350770177

@covidsafe-team its just semantics.. As others keep pushing for, please explain why you have not implemented using the Apple/Good frameworks??

**Comment by twasink** [comment]
It’s been explained in the Senate - the Australian Government doesn’t want a decentralised notification system. They want to use tools such as COVIDSafe to augment human-managed contact tracing.

There isn’t any conspiracy here. You can disagree with their rationale (I know I do), but the fact is that the Exposure Notification APIs don’t do what they want to achieve. Until they change what they want to achieve, it’s a dead argument.

**Comment by n0rt0nthec4t** [comment]
@twasink except, that app hasn't "achieved" its desired outcome of identifying covid contacts en-mass outside of the current  contact tracing system

**Comment by twasink** [comment]
I’ll avoid entering snark mode, and simply state that I never assumed that was the goal.

Nonetheless - until such time as the government changes their stance on having a centralised notification management system, the Exposure Notification API is a non-starter. There is zero point in asking for it.

If you wish to lobby the government to change their stance, then do so - but this isn’t the right forum. Nobody who actually works on this project has any authority over this.

**Comment by jarrodrobins** [comment]
> If you wish to lobby the government to change their stance, then do so - but this isn’t the right forum. Nobody who actually works on this project has any authority over this.

You are correct, there's little point discussing it in this forum. But, they have asked for developer feedback on Herald and it is appropriate to give them feedback on it - and it's a non-starter. They don't get a free pass just because they don't want to hear about the solution the operating system manufacturers built for them.

**Comment by HendX** [comment]
> but the fact is that the Exposure Notification APIs don’t do what they want to achieve.

Based on their comments about Exposure Notifications, it is clear they don't actually understand how it works. It can achieve what they want to achieve.

**Comment by covidsafe-team** [comment]
COVIDSafe has been updated to incorporate Herald. The reasons why we have chosen to use Herald are outlined in the release notes: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance.

**Comment by jarrodrobins** [comment]
Hi @covidsafe-team, this issue is not resolved by you implementing the Herald framework, and therefore needs to be reopened.

**Comment by yaakov-h** [comment]
I would just like to point out that in testimony on the 6th of May to the Senate Select Committee on COVID-19, Mr Randall Brugeaud, the CEO of the DTA, stated that:

> "we're aware of the performance issues as the app moves further into the background and are working with Apple and Google on the improvements that they're making to bluetooth, and we will be one of the first adopters of that improved bluetooth connectivity."

and:

> "Within a fortnight or thereabouts—it depends on the timing of the Apple bluetooth release—the performance will be as good in locked phones as it is in unlocked phones."

That was approximately 3 weeks before Exposure Notifications was released.

Where are these improvements if they are not a reference to Exposure Notifications? Or are you perhaps suggesting, @covidsafe-team, that your CEO lied to the Australian Senate?
