### ISSUE TITLE
Use of CoreLocation and CLLocationManager

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#30]
Please provide clear information about the use of location tracking in COVIDSafe Herald.

Reference: https://github.com/AU-COVIDSafe/mobile-ios/blob/herald/CovidSafe/Herald/Sensor/Location/AwakeSensor.swift

It should not be necessary for a Bluetooth key exchange application to require location tracking. On iOS, the Bluetooth permission is separate from the location permission.

If the app doesn’t actually gather the user’s location, then this appears to break the following App Store Review Guidelines, which are designed to protect users:

- 2.5.1: “Apps should use APIs and frameworks for their intended purposes and indicate that integration in their app description.”
- 2.5.4: “Multitasking apps may only use background services for their intended purposes.”

https://developer.apple.com/app-store/review/guidelines/

The recommended course of action is instead to use the Apple-Google Exposure Notification, which preserves user privacy and reliably exchanges Bluetooth keys without requiring access to CLLocationManager.

**Comment by mudlord** [comment]
>The recommended course of action is instead to use the Apple-Google Exposure Notification, which preserves user privacy and reliably exchanges Bluetooth keys without requiring access to CLLocationManager.

We know for obvious reasons thats never going to happen.

**Comment by HendX** [comment]
I just want to followup here about why not breaking the App Store rules is important, because it otherwise sounds like I'm just a dibber-dobber.

If you break these rules (potentially 2 different rules, for both misuse of CoreLocation and CoreBluetooth), even if you pass App Review the first time, there is a risk of not passing App Review for future update updates.

This poses a risk, since this may mean critical updates are not able to get through when required.

Note: Apple earlier this year said they wouldn't block critical updates due to rule violations, but in this instance, the app would subsequently likely need to remove such violations.

**Comment by covidsafe-team** [comment]
Apple and Google have approved the Herald update for release according to their App Guidelines. Further information about the Herald update can be found here: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance.
