### ISSUE TITLE
Battery usage in COVIDSafe Herald

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#31]
According to the following file:

https://github.com/AU-COVIDSafe/mobile-ios/blob/herald/CovidSafe/Herald/Sensor/BLE/BLEReceiver.swift

Two or more iPhones attempt to keep the app's Bluetooth system alive and running by a sending a keep-alive Bluetooth packet every 8 seconds.

I have two concerns about this workaround:

1. Similar to issue #30, it contravenes App Store Review Guidelines 2.5.1 and 2.5.4. It is not intended use of the Bluetooth system, and these rules are designed to protect users and their devices from developers from misusing Apple frameworks.

2. I have great concern about the impact this will on device battery life.

The following graphic shows the battery testing numbers, as published at https://www.dta.gov.au/news/covidsafe-captures-close-contacts-new-herald-protocol

<img width="790" alt="image" src="https://user-images.githubusercontent.com/525190/100672984-990ea080-33b2-11eb-9cf1-ba49bf5af9f2.png">

My suspicion is that these numbers are extremely conservative, given the 8 second keep-alive functionality. Especially in a situation where there are many iPhone users in close proximity for an extended period of time.

Please provide methodology and raw data for this chart. Specifically, it would be useful to see information such as:

1. What state was COVIDSafe in during the test, and for what period of time (e.g. screen on, screen off, backgrounded)
2. How many iPhones were present and in close proximity
3. How many Android phones were present and in close proximity

If the app uses too much battery, users will stop using it or uninstall it. The recommended approach is instead to adopt Apple/Google Exposure Notifications, which doesn't rely on these kinds of workarounds, is far more reliable, and is much gentler on users' devices.

**Comment by wabzqem** [comment]
![IMG_0041](https://user-images.githubusercontent.com/1582274/100674408-31a81f00-33b9-11eb-8387-47927cb66305.PNG)

For comparison, COVIDSafe-wabz is the herald version. The two were launched at the same time.

**Comment by yaakov-h** [comment]
In my testing (linked below) I observed a 19% drop in battery life in a single hour on an otherwise healthy iPhone 6s - at 90% of maximum battery capacity and capable of peak performance power draw.

https://github.com/AU-COVIDSafe/mobile-ios/issues/29#issuecomment-736531034

**Comment by yaakov-h** [comment]
Battery usage overnight on the same device is running at a constant 4% per hour. I suspect that while it was inside the microwave oven faraday cage it was consuming a lot more power trying to find a signal - I have seen similar behaviour of increased battery drain when in rural areas outside of network coverage.

4% per hour is still a full 25% above the DTA's published result above of 3.2% for the same model and will hardly be acceptable for the general public.

**Comment by HendX** [comment]
Thank you for clarifying this @yaakov-h. The iOS battery chart should indicate how much of this 19% was attributed to COVIDSafe though, right?

The real question then is how does it perform in the scenario with many iPhones in close proximity (e.g. in a shopping mall). Additionally, how will this impact the previously established iOS limit of 100 concurrent Bluetooth connections?

**Comment by yaakov-h** [comment]
The table below the iOS battery chart simply shows a dash for COVIDSafe's battery usage, rather than a percentage.

**Comment by kodekoala247** [comment]
Test on 2 android 2 ios old. 62000 rssi/12hr = 29 rssi/phone/min. Battery 1.1%, 1.4%/hr android, 1.5%, 2.4%/hr ios. Like dta results.

**Comment by HendX** [comment]
What about when you have 50-100 devices in close proximity (e.g. a mall or restaurant)?

**Comment by HendX** [comment]
(Point being that I agree that the code looks like battery life will be very similar for a small number of devices, but that is not what this issue related to)

**Comment by HendX** [comment]
Additionally, what impact will background location services have on the app? Perhaps none, but I presume all testing this far has a handful of devices sitting statically in an office somewhere, not roaming around the town, which is how the intended audience will likely use the device.

There's no mention of the impact of this in any battery results or chart.

I've asked for additional information about how testing was conducted. None has been forthcoming.

Maybe the DTA battery chart does account for this? Maybe it accounts for 100 devices in close proximity? I have no idea.

**Comment by egadsthefuzz** [comment]
Exactly, if we haven't been given the test specs we have to assume the least effort has been done as all previous testing on this project has not been very extensive.

**Comment by kodekoala247** [comment]
Used herald test proc. Location enabled on android ios. 50-100 in 1.5m radius? Rare. Rssi from ads. Payload from async read. Prob ok.

**Comment by covidsafe-team** [comment]
1. Apple and Google have approved the Herald update for release according to their App Guidelines. 
2. Battery usage summary results have been previously provided and indicate the results of Herald testing in real world conditions.

Further information about the Herald update can be found here: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance.
