### ISSUE TITLE
Herald: Permanent Display of Location Indicator

### ISSUE THREAD

**Issue by yaakov-h** [AU-COVIDSafe/mobile-ios#32]
On my iPhone 6s, COVIDSafe Herald appears to be permanently triggering the blue location-in-use status bar.

This will completely diminish the use and meaning of the background location indicator, and is likely to scare users and/or the media, particularly given the occasional message "COVIDSafe is Actively Using Your Location" from iOS.

This does not occur on my iPhone X or iPhone 12, so I assume iOS only does this on iPhones without the notch.

COVIDSafe only has the "While Using" permission and Precise Location disabled, on iOS 14.2 (18B92).

**Comment by covidsafe-team** [comment]
Thanks @yaakov-h  - this looks to be expected behavior. We will address this in our help topics for users
