### ISSUE TITLE
Summary of COVIDSafe Herald update for iOS

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#34]
Since today is Friday, and the timeline for releasing this update was "this week", here is a summary of the findings of the proposed update:

### Location Services

The app requests "while in background" location permissions (#30). This is a big no-no for a Government app. A significant number of users will not use the app because of this.

User can disable it, but then it removes one of the main workarounds for improving efficacy.

### Battery Concerns

Because of "keep-alive" packet sent every 8 seconds to all neighbouring iPhones, this update will have a non-neglible impact on users' batteries. (#31)

A significant number of users will stop using or uninstall the app because of battery drain.

### App Store Compliance

The above two points mean the app likely does not comply with [App Store rules 2.5.1 and 2.5.4](https://developer.apple.com/app-store/review/guidelines/). This poses a risk, because future critical updates may not be approved in a timely manner, or at all.

### Security

There are serious concerns raised in AU-COVIDSafe/mobile-android#30 about crytography in the app. Additionally, codebase isn't integrated as a third-party package (but rather, copied in). This will make merging upstream fixes difficult. This is a likely scenario. 

### Testing & Trials

It's unclear the testing methodologies and raw data that have been used to conclude items such as success rate of token exchange and battery usage.

Given that the supposedly improved key exchange rate is a result of location and bluetooth workarounds, it does not seem plausible that the app will improve performance over the non-Herald version.

In fact, it is entirely possible that a variation of #9 will surface due to the way the keep-alive works. This can't be verified yet, without a larger field trial and/or raw data to analyse.

### There is only one fix:

Migrate to Apple Google Exposure Notifications framework (https://covid19.apple.com/contacttracing)

**Personal Note**

Us developers you claim to want to engage with are tired over the hubris and stubbornness in relation to the current app and refusal to use ENF. It is a cause of stress, disbelief and exasperation.

You telling us this is going to work is like trying to convince us a circle is a square.

Stop disrespecting our time and expertise.

**Comment by dasvibes** [comment]
@HendX is 1000000000000% correct, if the developers of COVIDSafe really want to protect Australians and People in Australia, add or Migrate to Apple Google Exposure Notifications !!!

**Comment by covidsafe-team** [comment]
1. Apple and Google have approved the Herald update for release according to their App Guidelines. 
2. Battery usage summary results have been previously provided and indicate the results of Herald testing in real world conditions.
3. Testing results of battery and Bluetooth performance have been previously provided.
Further information about the Herald update and our approach to contact tracing can be found here: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance.

**Comment by HendX** [comment]
Let it be noted this issue has been closed without actually addressing the claims, especially that of Bluetooth efficacy.

**Comment by HendX** [comment]
Making an additional note to refer to potential reintroduction of #9.

Note that this possibility was raised well in advance of yesterday’s app release, and subsequently not acknowledged by @covidsafe-team here.
