### ISSUE TITLE
Add QR code support to increase Bluetooth background reliability

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#35]
I'd like to offer a constructive suggestion on how to increase the reliability of COVIDSafe with the current non-ENF Bluetooth solution:

**Add a QR code reader that is compatible with existing state-based QR codes**

This would result in users more frequently launching COVIDSafe, therefore improving its Bluetooth reliability, because:

1. **COVIDSafe won't relaunch after updating from the App Store.** If the user has automatic updates on, the app will be killed when updated and requires the user to manually relaunch.

2. **COVIDSafe may not automatically relaunch after reboot** (including when charging from a flat battery)

3. **Users would now be opening the app when they are in the highest risk situations**, such as when entering cafes or restaurants, therefore ensuring key exchange can take place.

Ideally this would have been included in the app initially, but since each state/territory now has their own solution, this could be implemented to work with the same QR codes and to record to the existing state-based databases.

I can't quantify how much this would increase the reliability of COVIDSafe, but it can't hurt, right?

**Comment by HendX** [comment]
A couple of additional thoughts on this:

* One the proposed Herald improvements is to (misuse) CoreLocation, which is a compliance risk. The above solution doesn't misuse any APIs

* I'm not 100% sure what happens after an iOS system update, in terms of app relaunch, but I wouldn't assume that any apps are relaunched.

* The QR code system could work in one of two ways:

1. Launch the scanned URL in Safari and allow manual check-in
2. Detect which app/state the QR code is for and launch the respective app directly onto the checkin screen for the scanned code.

I'm not actually sure what data is stored in the QR codes, so coordination with each state would likely be required to ensure there's a URL scheme to launch the app directly into the business details.

**Comment by covidsafe-team** [comment]
Thanks @HendX for your considered feedback. As [noted here](https://github.com/AU-COVIDSafe/mobile-android/issues/30#issuecomment-739706281 ) COVIDSafe will continue to focus on Bluetooth tracing. QR Code integration is not currently within the scope of COVIDSafe.
