### ISSUE TITLE
iOS 12 Updated to Support Exposure Notifications

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#36]
Apple:

> iOS 12.5 lets you opt-in to the COVID-19 Exposure Notifications system for your iPhone. System availability depends on support from your local public health authority. For more information see covid19.apple.com/contacttracing
This release also provides security updates and is recommended for all users.
For information on the security content of Apple software updates, please visit this 

https://support.apple.com/en-us/HT209084#12

This is extraordinary, and shows the level of dedication by Apple to this project.

**I implore you, once again, to reconsider your rejection of Exposure Notifications.**

I'd also like to be explicit here: ENF not supporting iOS 12 has been one of the DTA's excuses for not using it (even though ENF is far more reliable than COVIDSafe "working" on 100% of devices).

This iOS 12 update adds the following devices to the list of those that support Exposure Notifications

* iPhone 5S
* iPhone 6
* iPhone 6 Plus

According to https://developer.apple.com/support/app-store/ (not yet been updated for iOS 14):

<img width="337" alt="image" src="https://user-images.githubusercontent.com/525190/102145514-4a372f80-3eb7-11eb-96ec-103e6fcd2c4c.png">

This means that ENF is now supported on approximately 94% of all devices (up from about 88%).

**Comment by covidsafe-team** [comment]
Thanks @HendX  - we are aware of the changes to Exposure Notification Framework.
