### ISSUE TITLE
App does not automatically update

### ISSUE THREAD

**Issue by wabzqem** [AU-COVIDSafe/mobile-ios#41]
A number of my devices which had COVIDSafe 2.0 installed have not updated to 2.1.1, despite having auto update turned on for apps. Others have mentioned this as well:

![image0 png](https://user-images.githubusercontent.com/1582274/103160788-e0127900-482c-11eb-9912-b4959cf441ed.jpeg)

This reviewer has noticed something interesting; killing the app let it auto update. Now that COVIDSafe runs so effectively in the background, I wonder if you've run into the same problem that Android had - the OS won't update an app that is running. 

iOS doesn't expect apps to behave this way (and it looks like it may have some other unexpected side-effects, such as opportunistically triggering background updates in other applications more regularly), so it would be extremely interesting to understand Apple's position on this.

**Comment by egadsthefuzz** [comment]
I have run into this too. My 2.0 update to 2.1.1 only happened after my phone ran itself out of battery a few days ago and after restart I saw covidsafe update

**Comment by covidsafe-team** [comment]
Hi @wabzqem - thanks for raising this. We've made a change to our process, and the update alerts have been working more reliably for the last two releases.
