### ISSUE TITLE
Exposure Notifications API

### ISSUE THREAD

**Issue by balupton** [AU-COVIDSafe/mobile-ios#43]
The other issues were closed, so opening again as the root issue has not been resolved.

- https://github.com/AU-COVIDSafe/mobile-ios/issues/10
- https://github.com/AU-COVIDSafe/mobile-ios/issues/28
- https://github.com/AU-COVIDSafe/mobile-ios/issues/29
- https://github.com/AU-COVIDSafe/mobile-ios/issues/31
- https://github.com/AU-COVIDSafe/mobile-ios/issues/33
- https://github.com/AU-COVIDSafe/mobile-ios/issues/36

Furthermore, apps using ENF are doing swell: https://www.macrumors.com/2021/02/09/nhs-covid-app-1-7-million-self-isolate/

**Comment by covidsafe-team** [comment]
COVIDSafe has been updated to incorporate Herald. The reasons why we have chosen to use Herald are outlined in the release notes: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance.

**Comment by balupton** [comment]
I'm sorry, but you have responded to the wrong issue. This issue is about ENF not Herald.
