### ISSUE TITLE
COVIDSafe data 'incidentally' collected by intelligence agencies in first six months

### ISSUE THREAD

**Issue by balupton** [AU-COVIDSafe/mobile-ios#44]
> A spokesperson for the IGIS told iTnews that the “execution of warrants” was one such instance in which the incidental collection of Covid app data could occur.
>
> https://www.itnews.com.au/news/covidsafe-data-incidentally-collected-by-intelligence-agencies-in-first-six-months-558129

Coincidentally:

> Up until at least 18 June 2020, the DTA was experimenting with ENF,[109] however in an interview with The Project held on 28 June 2020, Deputy Chief Medical Officer Dr Nick Coatsworth stated **COVIDSafe would "absolutely not" transition to ENF**.[110] He reasoned the government would never transition to any contact tracing solution without human-in-the-loop reporting,[111][112] something that no decentralised protocol can support.
> 
> https://en.wikipedia.org/wiki/COVIDSafe

**Comment by covidsafe-team** [comment]
The Privacy Amendment (Public Health Contact Information) Act 2020 amends the Privacy Act (the Act) to provide stronger privacy protections for COVIDSafe app data. COVIDSafe app data can only be used for specific purposes, and only to the extent required for those purposes.

Under the Act, COVIDSafe app data can only be collected, used or disclosed for the purposes of:
•	state and territory health authorities undertaking contact tracing.
•	the Digital Transformation Agency (as the data store administrator):
o	enabling contact tracing by state and territory health authorities.
o	ensuring the proper functioning, integrity or security of the COVIDSafe app or National COVIDSafe Data Store.
o	using COVIDSafe app data to produce de-identified statistical information about the total number of registrations through the COVIDSafe app.
o	using COVIDSafe app data to confirm the correct data is being deleted, if a request has been made to delete the data.
•	the Australian Information Commissioner performing functions or exercising powers under the Act.
•	investigating or prosecuting a breach of the privacy protections under the Act.

The Act also:
•	prohibits anyone from requiring a person to download or use the COVIDSafe app. For example, an employer cannot make downloading or using the COVIDSafe app a condition of employment.
•	states the data held in the National COVIDSafe Data Store and COVIDSafe app data must be kept in Australia.
•	requires that the data store administrator delete all COVIDSafe app data held in the National COVIDSafe Data Store when the COVIDSafe app is no longer required, or is no longer likely to be effective as part of Australia’s response to COVID-19. The Minister for Health must determine this following consultation with the Commonwealth Chief Medical Officer or the Australian Health Protection Principal Committee.

Law enforcement agencies or the Australian Information Commissioner can only access COVIDSafe app data to enforce these privacy protections. They cannot use it for any other purpose.

If you think your privacy has been breached, you can make a complaint to the Office of the Australian Information Commissioner or the Australian Federal Police.
