### ISSUE TITLE
Recent high battery drain

### ISSUE THREAD

**Issue by CameronD73** [AU-COVIDSafe/mobile-ios#46]
I recently wrongly posted this to the herald-for-ios git page and was directed here.

The household has 2 iphones:

- a 6s running iOS 14.4; battery health: 50%
- a 6 running iOS 12.5.1; battery health: 87%
- Both running Covidsafe v2.2. We both tended to leave Covidsafe running permanently.

On Mon 15th Feb the 6s went flat overnight for the first time I can remember and then again on the following night. It had recently alerted the user that locations services need to be enabled.  Location services  on the 6 had been enabled for some time (can't recall when).

Checking battery usage graphs on both phones showed rapid steady battery decrease overnight and **the CPU running at 100%** in screen-off mode. With the phones' limited logging it is hard to say for certain, but the 10-day plot shows a definite change in background rates starting on Monday. Overnight the battery usage by app lists Covidsafe as the only app running but attributes a "-" as the percentage which I think means less than 1%. My interpretation of this is that the remainder is in the kernel itself. When I disable location services for covidsafe then this disappears - when I re-enable them then the 100% cpu usage returns.
I have just installed v2.3, build 111 and the issue is unchanged.  The 100% cpu applies even when location services are set to "while using".  On the 6 (the one with the good battery) I have just observed battery capacity drop from 75% to 55% in 4 hours with no screen-on activity.

**Comment by covidsafe-team** [comment]
Hi @CameronD73 
Thank you for the information - we have passed this on to the developer team. We continue to look for ways to optimise the performance of the app and these reports are quite helpful. 

The most recent iOS build is 2.3, so you can update to that version and see if this improves the performance on your devices. 
You may wish to contact our support team as they may be able to offer more detailed advice specific to your devices and usage. I will close this issue for now - you can reach out support team from within the app, or by email to support@covidsafe.gov.au .
Regards,
COVIDSafe team

**Comment by CameronD73** [comment]
the last part of my report was with V2.3 of the app.
