### ISSUE TITLE
App cannot be downloaded for iOS accounts with tenancy outside Australia

### ISSUE THREAD

**Issue by VegemiteJ** [AU-COVIDSafe/mobile-ios#48]
Use case: iOS account has US tenancy, but I'm attempting to use the app during travel within Australia.

App store doesn't allow the app to be downloaded unless I change region to Australia.
<img src="https://user-images.githubusercontent.com/10719569/113458931-be461500-945f-11eb-838b-c25b19cfe81d.png" height="600">

After changing region to Australia, fails to be downloaded with error indicating the account must be part of the US region (possibly due to existing purchases/subscriptions).
<img src="https://user-images.githubusercontent.com/10719569/113458944-c8681380-945f-11eb-9115-fdbe9251f2ee.png" height="600">

**Comment by covidsafe-team** [comment]
Hi @VegemiteJ ,
Can you please get in touch with our support team if you are still experiencing this issue as the app should be accessible in non-Australian app stores.
Kind regards,
COVIDSafe team
